using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public static class LootTable {

	//table for droppable items for each monster of each tier level.
	//format is:
	//<name of monster + tier level, <name of item, percent change to drop>>
	public static Dictionary<string, Dictionary<string, float>> lootTable = new Dictionary<string, Dictionary<string, float>>(){
		{"BullyTrunk1", 
			new Dictionary<string, float>(){
				{"money", 0f},
				{"sprint", 10f},
				{"roll", 0f},
				{"charge", 0f},
				{"lunge", 0f},
				{"riotShield", 0f},
				{"nanoTriangle", 0f},
				{"shockNet", 0f},
				{"chainGrab", 0f},
				{"flare", 0f},
				{"lantern", 0f},
				{"shiv", 0f},
				{"utilityBlade", 0f},
				{"pruningBlade", 0f},
				{"sixShooter", 0f},
				{"plasmaBlade", 0f},
				{"rebarSword", 0f},
				{"longSword", 0f},
				{"machette", 0f},
				{"thinBlade", 0f},
				{"flamePike", 0f},
				{"lumberSaw", 0f},
				{"chainsawSword", 0f},
				{"copGun", 0f},
				{"hiCompressionPistol", 0f},
				{"huntingRifle", 0f},
				{"laserRifle", 0f},
				{"machineGun", 0f},
				{"automaticLaserRifle", 0f},
				{"shotgun", 0f},
				{"wallOfLead", 0f},
				{"shirtAndPants", 0f},
				{"poncho", 0f},
				{"bulletProofVest", 0f},
				{"smugglersJacket", 0f},
				{"mixedPlateUniform", 0f},
				{"mixedArmyUniform", 0f},
				{"ceramicPlate", 0f},
				{"carbonFibronicMeshSuit", 0f},
				{"delversDuster", 0f},
				{"trashHelmetLightBulb", 0f},
				{"trashHelmetBucket", 0f},
				{"trafficCone", 0f},
				{"militarySpikeHelmet", 0f},
				{"bikerHelmet", 0f},
				{"policeHelmet", 0f},
				{"comHelmet", 0f},
				{"targetingVisor", 0f},
				{"bionicEye", 0f},
				{"cyberFaceRobot", 0f},
				{"cyberFaceHorns", 0f},
				{"brainCaseVisor", 0f}
			}
		},
		{"FoliantFodder2", 
			new Dictionary<string, float>(){
				{"money", 0f},
				{"sprint", 0f},
				{"roll", 0f},
				{"charge", 0f},
				{"lunge", 0f},
				{"riotShield", 0f},
				{"nanoTriangle", 0f},
				{"shockNet", 0f},
				{"chainGrab", 0f},
				{"flare", 0f},
				{"lantern", 0f},
				{"shiv", 0f},
				{"utilityBlade", 0f},
				{"pruningBlade", 0f},
				{"sixShooter", 0f},
				{"plasmaBlade", 0f},
				{"rebarSword", 0f},
				{"longSword", 0f},
				{"machette", 0f},
				{"thinBlade", 0f},
				{"flamePike", 0f},
				{"lumberSaw", 0f},
				{"chainsawSword", 0f},
				{"copGun", 0f},
				{"hiCompressionPistol", 0f},
				{"huntingRifle", 0f},
				{"laserRifle", 0f},
				{"machineGun", 0f},
				{"automaticLaserRifle", 0f},
				{"shotgun", 0f},
				{"wallOfLead", 0f},
				{"shirtAndPants", 0f},
				{"poncho", 0f},
				{"bulletProofVest", 0f},
				{"smugglersJacket", 0f},
				{"mixedPlateUniform", 0f},
				{"mixedArmyUniform", 0f},
				{"ceramicPlate", 0f},
				{"carbonFibronicMeshSuit", 0f},
				{"delversDuster", 0f},
				{"trashHelmetLightBulb", 0f},
				{"trashHelmetBucket", 0f},
				{"trafficCone", 0f},
				{"militarySpikeHelmet", 0f},
				{"bikerHelmet", 0f},
				{"policeHelmet", 0f},
				{"comHelmet", 0f},
				{"targetingVisor", 0f},
				{"bionicEye", 0f},
				{"cyberFaceRobot", 0f},
				{"cyberFaceHorns", 0f},
				{"brainCaseVisor", 0f}
			}
		},
		{"FoliantFodder3", 
			new Dictionary<string, float>(){
				{"money", 0f},
				{"sprint", 0f},
				{"roll", 0f},
				{"charge", 0f},
				{"lunge", 0f},
				{"riotShield", 0f},
				{"nanoTriangle", 0f},
				{"shockNet", 0f},
				{"chainGrab", 0f},
				{"flare", 0f},
				{"lantern", 0f},
				{"shiv", 0f},
				{"utilityBlade", 0f},
				{"pruningBlade", 0f},
				{"sixShooter", 0f},
				{"plasmaBlade", 0f},
				{"rebarSword", 0f},
				{"longSword", 0f},
				{"machette", 0f},
				{"thinBlade", 0f},
				{"flamePike", 0f},
				{"lumberSaw", 0f},
				{"chainsawSword", 0f},
				{"copGun", 0f},
				{"hiCompressionPistol", 0f},
				{"huntingRifle", 0f},
				{"laserRifle", 0f},
				{"machineGun", 0f},
				{"automaticLaserRifle", 0f},
				{"shotgun", 0f},
				{"wallOfLead", 0f},
				{"shirtAndPants", 0f},
				{"poncho", 0f},
				{"bulletProofVest", 0f},
				{"smugglersJacket", 0f},
				{"mixedPlateUniform", 0f},
				{"mixedArmyUniform", 0f},
				{"ceramicPlate", 0f},
				{"carbonFibronicMeshSuit", 0f},
				{"delversDuster", 0f},
				{"trashHelmetLightBulb", 0f},
				{"trashHelmetBucket", 0f},
				{"trafficCone", 0f},
				{"militarySpikeHelmet", 0f},
				{"bikerHelmet", 0f},
				{"policeHelmet", 0f},
				{"comHelmet", 0f},
				{"targetingVisor", 0f},
				{"bionicEye", 0f},
				{"cyberFaceRobot", 0f},
				{"cyberFaceHorns", 0f},
				{"brainCaseVisor", 0f}
			}
		},
		{"FoliantFodder4", 
			new Dictionary<string, float>(){
				{"money", 0f},
				{"sprint", 0f},
				{"roll", 0f},
				{"charge", 0f},
				{"lunge", 0f},
				{"riotShield", 0f},
				{"nanoTriangle", 0f},
				{"shockNet", 0f},
				{"chainGrab", 0f},
				{"flare", 0f},
				{"lantern", 0f},
				{"shiv", 0f},
				{"utilityBlade", 0f},
				{"pruningBlade", 0f},
				{"sixShooter", 0f},
				{"plasmaBlade", 0f},
				{"rebarSword", 0f},
				{"longSword", 0f},
				{"machette", 0f},
				{"thinBlade", 0f},
				{"flamePike", 0f},
				{"lumberSaw", 0f},
				{"chainsawSword", 0f},
				{"copGun", 0f},
				{"hiCompressionPistol", 0f},
				{"huntingRifle", 0f},
				{"laserRifle", 0f},
				{"machineGun", 0f},
				{"automaticLaserRifle", 0f},
				{"shotgun", 0f},
				{"wallOfLead", 0f},
				{"shirtAndPants", 0f},
				{"poncho", 0f},
				{"bulletProofVest", 0f},
				{"smugglersJacket", 0f},
				{"mixedPlateUniform", 0f},
				{"mixedArmyUniform", 0f},
				{"ceramicPlate", 0f},
				{"carbonFibronicMeshSuit", 0f},
				{"delversDuster", 0f},
				{"trashHelmetLightBulb", 0f},
				{"trashHelmetBucket", 0f},
				{"trafficCone", 0f},
				{"militarySpikeHelmet", 0f},
				{"bikerHelmet", 0f},
				{"policeHelmet", 0f},
				{"comHelmet", 0f},
				{"targetingVisor", 0f},
				{"bionicEye", 0f},
				{"cyberFaceRobot", 0f},
				{"cyberFaceHorns", 0f},
				{"brainCaseVisor", 0f}
			}
		},
		{"FoliantFodder5", 
			new Dictionary<string, float>(){
				{"money", 0f},
				{"sprint", 0f},
				{"roll", 0f},
				{"charge", 0f},
				{"lunge", 0f},
				{"riotShield", 0f},
				{"nanoTriangle", 0f},
				{"shockNet", 0f},
				{"chainGrab", 0f},
				{"flare", 0f},
				{"lantern", 0f},
				{"shiv", 0f},
				{"utilityBlade", 0f},
				{"pruningBlade", 0f},
				{"sixShooter", 0f},
				{"plasmaBlade", 0f},
				{"rebarSword", 0f},
				{"longSword", 0f},
				{"machette", 0f},
				{"thinBlade", 0f},
				{"flamePike", 0f},
				{"lumberSaw", 0f},
				{"chainsawSword", 0f},
				{"copGun", 0f},
				{"hiCompressionPistol", 0f},
				{"huntingRifle", 0f},
				{"laserRifle", 0f},
				{"machineGun", 0f},
				{"automaticLaserRifle", 0f},
				{"shotgun", 0f},
				{"wallOfLead", 0f},
				{"shirtAndPants", 0f},
				{"poncho", 0f},
				{"bulletProofVest", 0f},
				{"smugglersJacket", 0f},
				{"mixedPlateUniform", 0f},
				{"mixedArmyUniform", 0f},
				{"ceramicPlate", 0f},
				{"carbonFibronicMeshSuit", 0f},
				{"delversDuster", 0f},
				{"trashHelmetLightBulb", 0f},
				{"trashHelmetBucket", 0f},
				{"trafficCone", 0f},
				{"militarySpikeHelmet", 0f},
				{"bikerHelmet", 0f},
				{"policeHelmet", 0f},
				{"comHelmet", 0f},
				{"targetingVisor", 0f},
				{"bionicEye", 0f},
				{"cyberFaceRobot", 0f},
				{"cyberFaceHorns", 0f},
				{"brainCaseVisor", 0f}
			}
		}
	};

}
