//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class MusicController: MonoBehaviour {
	public List<Character> areaUnits;
	public Player[] allPlayers;
	public bool same;
	public int enemyCount;
	
	private AudioSource battle;
	private AudioSource environment;

	void Start () {
		GetComponent<Transform>();
		allPlayers = FindObjectsOfType(typeof(Player)) as Player[];
		for(int x = 0; x < allPlayers.Length; x++){
			areaUnits.Add(allPlayers[x]);
		}
		environment = GameObject.Find ("PerspectiveAngledCamera").GetComponent<AudioSource> ();
		battle = GetComponent<AudioSource> ();
	}

	// Update is called once per frame
	void Update () {
		
		if (enemyCount > 0 && !battle.isPlaying) {
			environment.Pause ();
			environment.volume = 0;
			battle.Play ();
		} else if (enemyCount == 0 && battle.isPlaying) {
			if (TransitionOut (battle, 0.7f, 0))
				environment.UnPause ();
		} else if (environment.volume < 1 && environment.isPlaying) {
			TransitionIn(environment, 0.3f, 1);
		}
	}

	bool TransitionIn(AudioSource musik, float rate, float done) {
		if(musik.volume < 0.2f) musik.volume += 0.1f * Time.deltaTime;
		else if (musik.volume < done) musik.volume += rate * Time.deltaTime;
		return musik.volume >= done;
	}
	
	bool TransitionOut(AudioSource musik, float rate, float done) {
		if (musik.volume > 0.2f) musik.volume -= rate * Time.deltaTime;
		else if (musik.volume > done) musik.volume -= 0.1f * Time.deltaTime;
		
		if(musik.volume <= done) {
			musik.Stop();
			musik.volume = 1;
			return true;
		}
		return false;
	}
}
