//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class UIButtonSetup : MonoBehaviour {
	void Start(){

		Button btn;

		btn = GameObject.Find("Button_Room").GetComponent("Button") as Button;
		btn.onClick.AddListener(() => {
			Camera.main.GetComponent<TileMapController>().fillInRoom(); });


		btn = GameObject.Find ("Button_ZoomOut").GetComponent("Button") as Button;
		btn.onClick.AddListener (() => {
			Camera.main.GetComponent<CameraMovement>().zoomCamIn ();});

		btn = GameObject.Find ("Button_ZoomIn").GetComponent("Button") as Button;
		btn.onClick.AddListener (() => {
			Camera.main.GetComponent<CameraMovement>().zoomCamOut ();});

		btn = GameObject.Find ("Button_ModeToggle").GetComponent("Button") as Button;
		btn.onClick.AddListener (() => {
			if(Mode.isRoomMode())
				Mode.setTileMode();
			else if(Mode.isTileMode())
				Mode.setRoomMode();
		});

		btn = GameObject.Find ("Button_CameraToggle").GetComponent("Button") as Button;
		btn.onClick.AddListener(() => {
			if(Camera.main.orthographic){
				Camera.main.GetComponent<CameraMovement>().changeToPerspective();
				btn.GetComponent<Image>().sprite = Resources.Load <Sprite>("LevelEditorIcons/perspe");
			}
			else{
				Camera.main.GetComponent<CameraMovement>().changeToTopDown();
				btn.GetComponent<Image>().sprite = Resources.Load <Sprite>("LevelEditorIcons/orthog");
			}
		});
	}
}
